import { useEffect, useState } from "react";
import api, { formatApiError } from "../lib/api";
import { Page, Card, EmptyState, Spinner } from "../components/common";
import { Button } from "../components/ui/button";
import { CheckCircle2, XCircle, RotateCcw, Trophy, FileText, Sparkles } from "lucide-react";
import { toast } from "sonner";

export default function Quiz() {
  const [pdfs, setPdfs] = useState(null); const [pdfId, setPdfId] = useState("");
  const [difficulty, setDifficulty] = useState("medium"); const [count, setCount] = useState("5");
  const [questions, setQuestions] = useState(null); const [answers, setAnswers] = useState({});
  const [result, setResult] = useState(null); const [loading, setLoading] = useState(false);
  useEffect(() => { api.get("/pdfs").then((r) => setPdfs(r.data)).catch(() => setPdfs([])); }, []);

  const generate = async () => { if (!pdfId) return toast.error("Select a Biology PDF first"); setLoading(true); setResult(null); setAnswers({});
    try { const { data } = await api.get("/quiz/generate", { params: { pdf_id: pdfId, difficulty, count } }); setQuestions(data.questions); }
    catch (err) { toast.error(formatApiError(err.response?.data?.detail)); } finally { setLoading(false); }
  };
  const submit = async () => { setLoading(true);
    const payload = questions.map((q, i) => ({ question: q.question, selected: answers[i] || "", correct_answer: q.correct_answer, correct: answers[i] === q.correct_answer, concepts: q.concepts, explanation: q.explanation, topic: q.topic }));
    try { const { data } = await api.post("/quiz/submit", { pdf_id: pdfId, topic: "uploaded_pdf", answers: payload }); setResult(data); }
    catch (err) { toast.error(formatApiError(err.response?.data?.detail)); } finally { setLoading(false); }
  };
  const reset = () => { setQuestions(null); setResult(null); setAnswers({}); };
  if (pdfs === null) return <Page title="Study Notes Quiz"><Spinner /></Page>;
  return <Page title="Study Notes Quiz" subtitle="Questions generated from your uploaded document" testid="quiz-page">
    {!questions && !result && <div className="grid lg:grid-cols-[1.15fr_.85fr] gap-6 max-w-5xl">
      <Card className="bg-pink-50/70 border-pink-100"><div className="h-12 w-12 rounded-2xl bg-white flex items-center justify-center mb-5"><Sparkles className="h-6 w-6 text-pink-500" /></div><h2 className="text-2xl font-bold">Build a new quiz</h2><p className="text-sm text-muted-foreground mt-2 max-w-md">Questions are built from sentences and key terms extracted from the selected study document. Previous questions are remembered so your next session stays fresh.</p><div className="mt-8 space-y-5"><label className="block text-sm font-semibold">Study document<select value={pdfId} onChange={(e) => setPdfId(e.target.value)} className="mt-2 h-11 w-full rounded-md border border-pink-200 bg-white px-3 text-sm" data-testid="quiz-pdf-select"><option value="">Choose uploaded notes</option>{pdfs.map((p) => <option key={p.id} value={p.id}>{p.filename} · {p.num_units ?? p.num_pages} {p.document_type === "pptx" ? "slides" : p.document_type === "xlsx" ? "sheets" : p.document_type === "pdf" ? "pages" : "sections"}</option>)}</select></label><div className="grid sm:grid-cols-2 gap-4"><label className="block text-sm font-semibold">Difficulty<select value={difficulty} onChange={(e) => setDifficulty(e.target.value)} className="mt-2 h-11 w-full rounded-md border border-pink-200 bg-white px-3 text-sm" data-testid="quiz-difficulty-select"><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></label><label className="block text-sm font-semibold">Questions<select value={count} onChange={(e) => setCount(e.target.value)} className="mt-2 h-11 w-full rounded-md border border-pink-200 bg-white px-3 text-sm" data-testid="quiz-count-select">{[3,5,8,10].map((n) => <option key={n}>{n}</option>)}</select></label></div><Button onClick={generate} disabled={loading || !pdfs.length} data-testid="quiz-start">{loading ? <Spinner /> : <><Sparkles className="h-4 w-4" /> Generate questions from document</>}</Button></div></Card>
      <Card><h3 className="font-bold">How it stays grounded</h3><div className="mt-5 space-y-4 text-sm text-muted-foreground"><p className="flex gap-3"><FileText className="h-5 w-5 text-sky-500 shrink-0" /> Questions use only extracted sentences and terms from your chosen document.</p><p className="flex gap-3"><RotateCcw className="h-5 w-5 text-pink-500 shrink-0" /> Question history prevents repeats for this student and document.</p><p className="flex gap-3"><Trophy className="h-5 w-5 text-violet-500 shrink-0" /> Results include explanations and weak concepts to revisit.</p></div>{!pdfs.length && <EmptyState title="Upload notes first" description="Your uploaded Biology study documents will appear here." testid="quiz-no-pdfs" />}</Card>
    </div>}
    {questions && !result && <div className="max-w-4xl space-y-5" data-testid="quiz-questions"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold">{questions.length} questions · {difficulty}</p><p className="text-xs text-muted-foreground">Answer from what you learned in the selected PDF.</p></div><Button variant="outline" onClick={reset} data-testid="quiz-cancel">Cancel</Button></div>{questions.map((q, i) => <Card key={i} data-testid={`quiz-question-${i}`}><p className="text-xs uppercase tracking-wider text-pink-500 font-bold mb-2">{q.type || "concept"}</p><p className="font-semibold leading-6 mb-4">{i + 1}. {q.question}</p>{q.options?.length ? <div className="grid gap-2">{q.options.map((option) => <button key={option} onClick={() => setAnswers((a) => ({ ...a, [i]: option }))} className={`w-full text-left px-4 py-3 rounded-lg border text-sm transition-colors ${answers[i] === option ? "border-pink-400 bg-pink-50" : "border-border hover:border-sky-300 hover:bg-sky-50/50"}`} data-testid={`quiz-q${i}-option-${q.options.indexOf(option)}`}>{option}</button>)}</div> : <input value={answers[i] || ""} onChange={(e) => setAnswers((a) => ({ ...a, [i]: e.target.value }))} className="h-11 w-full rounded-md border border-input px-3 text-sm" placeholder="Write your answer…" data-testid={`quiz-q${i}-input`} />}</Card>)}<Button onClick={submit} disabled={loading || Object.keys(answers).length !== questions.length} data-testid="quiz-submit">{loading ? <Spinner /> : "Submit quiz"}</Button></div>}
    {result && <div className="max-w-4xl space-y-5" data-testid="quiz-result"><Card className="bg-pink-50/70 border-pink-100 text-center"><Trophy className="h-10 w-10 mx-auto text-pink-500 mb-3" /><p className="text-5xl font-black">{result.percentage}%</p><p className="text-sm text-muted-foreground mt-2">{result.correct} correct · {result.incorrect} incorrect · {result.total} total</p><p className="text-sm mt-4">{result.recommendation}</p></Card><div className="space-y-3">{questions.map((q, i) => { const correct = answers[i] === q.correct_answer; return <Card key={i} data-testid={`quiz-review-${i}`}><div className="flex gap-3">{correct ? <CheckCircle2 className="h-5 w-5 text-emerald-500 shrink-0" /> : <XCircle className="h-5 w-5 text-rose-500 shrink-0" />}<div><p className="font-semibold">{q.question}</p><p className="text-sm mt-2"><span className="text-muted-foreground">Correct answer: </span>{q.correct_answer}</p>{!correct && <p className="text-sm text-muted-foreground mt-2"><span className="font-medium text-foreground">Why: </span>{q.explanation}</p>}</div></div></Card>; })}</div><Button onClick={reset} data-testid="quiz-retry"><RotateCcw className="h-4 w-4" /> New PDF quiz</Button></div>}
  </Page>;
}